name: TimeCommand
version: ${project.version}
main: net.dohaw.timecommand.TimeCommandPlugin

commands:
  timecommand:
    description: The base command for this plugin
    permission: timecommand.use
    aliases:
      - tc
      - timec
      - tcommand
      - tco
permissions:
  timecommand.use:
    default: op
